name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./dev/front/plan.io

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Check out the repository
      - uses: actions/checkout@v4
      - name: Path
        run: echo $PATH
      - name: PWD
        run: echo pwd
      - name: Change Directory
        run: cd ../dev/front/plan.io
      
      # Set up Node.js environment and cache npm dependencies
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci
      
      # Build the project (if applicable)
      - name: Build Project
        run: npm run build --if-present

      # Run tests
      - name: Run Tests
        run: npm test

      # Upload test results (optional)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/

      # Clean up npm cache (optional)
      - name: Clean up npm cache
        run: npm cache clean --force
